/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as DisplayIdRouteImport } from './routes/display.$id'
import { Route as BrowseResultsRouteImport } from './routes/browse/results'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayIdRoute = DisplayIdRouteImport.update({
  id: '/display/$id',
  path: '/display/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseResultsRoute = BrowseResultsRouteImport.update({
  id: '/browse/results',
  path: '/browse/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/links': typeof LinksRoute
  '/browse/results': typeof BrowseResultsRoute
  '/display/$id': typeof DisplayIdRoute
  '/browse': typeof BrowseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/links': typeof LinksRoute
  '/browse/results': typeof BrowseResultsRoute
  '/display/$id': typeof DisplayIdRoute
  '/browse': typeof BrowseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/links': typeof LinksRoute
  '/browse/results': typeof BrowseResultsRoute
  '/display/$id': typeof DisplayIdRoute
  '/browse/': typeof BrowseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/copyright'
    | '/links'
    | '/browse/results'
    | '/display/$id'
    | '/browse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/copyright'
    | '/links'
    | '/browse/results'
    | '/display/$id'
    | '/browse'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/copyright'
    | '/links'
    | '/browse/results'
    | '/display/$id'
    | '/browse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CopyrightRoute: typeof CopyrightRoute
  LinksRoute: typeof LinksRoute
  BrowseResultsRoute: typeof BrowseResultsRoute
  DisplayIdRoute: typeof DisplayIdRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$id': {
      id: '/display/$id'
      path: '/display/$id'
      fullPath: '/display/$id'
      preLoaderRoute: typeof DisplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/results': {
      id: '/browse/results'
      path: '/browse/results'
      fullPath: '/browse/results'
      preLoaderRoute: typeof BrowseResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CopyrightRoute: CopyrightRoute,
  LinksRoute: LinksRoute,
  BrowseResultsRoute: BrowseResultsRoute,
  DisplayIdRoute: DisplayIdRoute,
  BrowseIndexRoute: BrowseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
